In [2]:
# %load lab11_2_embd.py
import numpy as np
old = np.load
np.load = lambda *a,**k: old(*a,**k,allow_pickle=True)

from keras.datasets import reuters
(train_data, train_labels), (test_data, test_labels) = reuters.load_data(num_words=10000)

np.load = old
del(old)

from keras.layers import Embedding
from keras import preprocessing

x_train = preprocessing.sequence.pad_sequences(train_data)
x_test = preprocessing.sequence.pad_sequences(test_data)
########################################################################
from keras.utils import np_utils
y_train = np_utils.to_categorical(train_labels)
print('x_train', x_train)
print('y_train', y_train)

maxlen = 0
for element in x_train[0:]:
    if maxlen < len(element):
        maxlen = len(element)

print('maxlen: ', maxlen)
########################################################################
from keras.models import Sequential
from keras import layers

model = Sequential()
model.add(Embedding(10000, 8, input_length=maxlen))
model.add(layers.Flatten())
model.add(layers.Dense(46, activation='softmax'))
model.compile(optimizer='rmsprop', loss='categorical_crossentropy',
              metrics=['accuracy'])

####################################################################
import keras

callback_list = [
    keras.callbacks.EarlyStopping( #성능 향상이 멈추면 훈련을 중지
         monitor='val_acc',  #모델 검증 정확도를 모니터링
         patience=1          #1 에포크 보다 더 길게(즉, 2에포크 동안 정확도가 향상되지 않으면 훈련 중지
    ),
    keras.callbacks.ModelCheckpoint ( #에포크마다 현재 가중치를 저장
        filepath="embedding_model_h5",   #모델 파일 경로
        monitor="val_loss",    # val_loss 가 좋아지지 않으면 모델 파일을 덮어쓰지 않음.
        save_best_only=True
    )
]

import os
from keras.models import load_model
if os.path.exists("embedding_model_h5") :
    model =load_model( "embedding_model_h5")

history = model.fit(x_train,
                    y_train,
                    epochs=10,
                    callbacks=callback_list ,
                    batch_size=64,
                    validation_split=0.2)




Using TensorFlow backend.
W0806 17:32:50.589839  1080 deprecation_wrapper.py:119] From C:\Users\user\Anaconda3\envs\deeplearning\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0806 17:32:50.589839  1080 deprecation_wrapper.py:119] From C:\Users\user\Anaconda3\envs\deeplearning\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0806 17:32:50.589839  1080 deprecation_wrapper.py:119] From C:\Users\user\Anaconda3\envs\deeplearning\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0806 17:32:50.621118  1080 deprecation_wrapper.py:119] From C:\Users\user\Anaconda3\envs\deeplearning\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimi

x_train [[  0   0   0 ...  15  17  12]
 [  0   0   0 ... 505  17  12]
 [  0   0   0 ...  11  17  12]
 ...
 [  0   0   0 ... 407  17  12]
 [  0   0   0 ... 364  17  12]
 [  0   0   0 ... 113  17  12]]
y_train [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
maxlen:  2376
Train on 7185 samples, validate on 1797 samples
Epoch 1/10
7185/7185 [==============================] - 2s 330us/step - loss: 2.2147 - acc: 0.4347 - val_loss: 2.0108 - val_acc: 0.5053
Epoch 2/10
7185/7185 [==============================] - 2s 284us/step - loss: 1.8393 - acc: 0.5439 - val_loss: 1.7623 - val_acc: 0.5648
Epoch 3/10
7185/7185 [==============================] - 2s 281us/step - loss: 1.5849 - acc: 0.6036 - val_loss: 1.6407 - val_acc: 0.6132
Epoch 4/10
7185/7185 [==============================] - 2s 270us/step - loss: 1.3717 - acc: 0.6683 - val_loss: 1.5487 - val_acc: 0.6361
Epoch 5/10
7185/7185 [========